# Generated by Django 2.0.6 on 2019-02-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ImageField(default='none', upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200)),
                ('image', models.ImageField(default='none', upload_to='uploads/')),
            ],
            options={
                'verbose_name_plural': 'pic',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(default='none', to='im_galery.picture', verbose_name='pic'),
        ),
    ]
