# Generated by Django 2.0.6 on 2019-02-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im_galery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='photos',
        ),
        migrations.AlterField(
            model_name='album',
            name='poster',
            field=models.ImageField(default='none', upload_to='media/'),
        ),
        migrations.DeleteModel(
            name='picture',
        ),
    ]
